### ISSUE TITLE
line 8, column 87: This is not an EAGLE file.

### ISSUE THREAD

**Issue by thijsdeschildre** [SolderedElectronics/Lithium-ion-charger-with-protection---Eagle-files#1]
I can't open the .sch file.
I've tried Eagle 8.7.1, 9.0.0 and 9.6.2
In the end, I copypasted the .brd and .sch code from my browser to a textfile, which works

**Comment by davidzovko** [comment]
Hi, we use Eagle 7.3.0, it's an older version still when Eagle was Cadsoft's product. Maybe that's the reason. 

Glad to hear that you have found the way, though!
